//? try catch => error handling

const x = 5;

try {
  x = 10;
} catch (error) {
  console.log(error.message);
}
console.log("Hello 1");
console.log("Kathmandu");
